[package]
name = "rust_web_scrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
reqwest = "0.12.5"
select = "0.6.0"
tokio = { version = "1.38.0", features = ["full"] }
csv = "1.1.6"
